# nixpacks.toml — автовыгрузка из VK перед импортом в БД

[variables]
# Python 3.12 — совместим с aiogram/pydantic
NIXPACKS_PYTHON_VERSION = "3.12"

[phases.setup]
# python + gcc (некоторым колёсам нужен компилятор)
nixPkgs = ["python312", "gcc"]

[phases.install]
# создаём venv и ставим зависимости
cmds = [
  "python -m venv .venv",
  ". .venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
# 1) тянем товары из VK -> products_template.csv
# 2) создаём/обновляем схему БД
# 3) импортируем CSV в SQLite
cmds = [
  ". .venv/bin/activate && python vk_export.py --owner $VK_OWNER_ID --token $VK_ACCESS_TOKEN --out products_template.csv",
  ". .venv/bin/activate && python init_db.py || true",
  ". .venv/bin/activate && python seed_from_csv.py --csv products_template.csv --clear"
]

[start]
# запускаем бота + веб-витрину
cmd = ". .venv/bin/activate && python bot.py"

